apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone-producer
  labels:
    script: standalone-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      script: standalone-producer
  template:
    metadata:
      labels:
        script: standalone-producer
    spec:
      containers:
      - name: standalone-producer
        env:
        - name: duration_in_seconds
          value: "20"
        command: ["python", "producer.py", "-p", "5672", "-s", "rabbitmq"]
        args: ["-t", "$(duration_in_seconds)"]
        image: samer1984/app_producer-with-duration:latest
      restartPolicy: Always
