apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        ports:
        - name: api-port
          containerPort: 5672
        - name: gui-port
          containerPort: 15672
      - image: kbudde/rabbitmq-exporter
        name: rabbitmq-exporter
        ports:
        - name: exporter-port
          containerPort: 9422
      restartPolicy: Always
