apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        env:
        - name: PUBLISH_PORT
          value: "9422"
        - name: RABBIT_USER
          value: "guest"
        - name: RABBIT_PASSWORD
          value: "guest"
        - name: RABBIT_URL
          value: http://rabbitmq:15672
        - name: INCLUDE_QUEUES
          value: ".*"
        ports:
        - name: exporter-port
          containerPort: 9422
      restartPolicy: Always
