apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9422'
    prometheus.io/path: "/metrics"
spec:
  ports:
  - name: api-daemon-port
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: gui-port
    port: 15672
    targetPort: 15672
    protocol: TCP
  - name: exporter-port
    port: 9422
    targetPort: exporter-port
    protocol: TCP
  selector:
    app: rabbitmq
