apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9422'
    prometheus.io/path: "/metrics"
spec:
  ports:
  - name: rabbitmq-exp-port
    port: 9422
    targetPort: exporter-port
    protocol: TCP
  selector:
    app: rabbitmq
